CREATE TABLE IF NOT EXISTS Jernbanestasjon (
	Navn TEXT PRIMARY KEY,
	Høyde REAL
);

CREATE TABLE IF NOT EXISTS GårMellom (
	StrekningsID INTEGER PRIMARY KEY,
	Navn1 TEXT,
	Navn2 TEXT,
	FOREIGN KEY (Navn1) REFERENCES Jernbanestasjon(Navn)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (Navn2) REFERENCES Jernbanestasjon(Navn)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Delstrekning (
	StrekningsID INTEGER PRIMARY KEY,
	Lengde REAL,
	Dobbeltspor BOOLEAN,
	FOREIGN KEY (StrekningsID) REFERENCES GårMellom(StrekningsID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Banestrekning (
	Navn TEXT PRIMARY KEY,
	Elektrisk BOOLEAN,
	HovedretningFra TEXT,
	FOREIGN KEY (HovedretningFra) REFERENCES Jernbanestasjon(Navn)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DelAv (
	Navn TEXT,
	StrekningsID INTEGER,
	PRIMARY KEY (Navn, StrekningsID),
	FOREIGN KEY (Navn) REFERENCES Banestrekning(Navn)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (StrekningsID) REFERENCES Delstrekning(StrekningsID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Operatør (
	Navn TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Vogntog (
	VognTogID INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS BestårAv (
	VognID INTEGER ,
	VognTogID INTEGER,
	PRIMARY KEY (VognID, VognTogID),
	FOREIGN KEY (VognTogID) REFERENCES Vogntog(VognTogID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (VognID) REFERENCES Vogn(VognID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VognType (
	VognNavn TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Sittevogn (
	VognNavn TEXT PRIMARY KEY,
	FOREIGN KEY (VognNavn) REFERENCES VognType(VognNavn)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Sovevogn (
	VognNavn TEXT PRIMARY KEY,
	FOREIGN KEY (VognNavn) REFERENCES VognType(VognNavn)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Seng (
	SengNr INTEGER PRIMARY KEY,
	KupeNr INTEGER,
	VognNavn TEXT,
	FOREIGN KEY (KupeNr) REFERENCES Kupé(KupeNr)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE,
	FOREIGN KEY (VognNavn) REFERENCES Sovevogn(VognNavn)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Sete (
	SeteNr INTEGER PRIMARY KEY,
	RadNr INTEGER,
	VognNavn TEXT,
	FOREIGN KEY (VognNavn) REFERENCES Sittevogn(VognNavn)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Togrute (
	RuteID INTEGER PRIMARY KEY,
	OperatørNavn TEXT,
	VognTogID INTEGER,
	FOREIGN KEY (OperatørNavn) REFERENCES Operatør(Navn)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (VognTogID) REFERENCES Vogntog(VognTogID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS KjørerPå (
	RuteID INTEGER,
	Navn TEXT,
	PRIMARY KEY (RuteID, Navn),
	FOREIGN KEY (RuteID) REFERENCES Togrute(RuteID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (Navn) REFERENCES Banestrekning(Navn)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Ruteforekomst (
  Ukedag TEXT,
  RuteID INTEGER,
  PRIMARY KEY (Ukedag, RuteID),
  FOREIGN KEY (RuteID) REFERENCES Togrute(RuteID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS RuteTabell (
	TabellID INTEGER, 
	Jernbanestasjon TEXT, 
	AvgangsTid TEXT, 
	AnkomstTid TEXT,
	PRIMARY KEY (TabellID, Jernbanestasjon),
	FOREIGN KEY (Jernbanestasjon) REFERENCES Jernbanestasjon(Navn)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HarRute (
	RuteID INTEGER,
	TabellID INTEGER,
	PRIMARY KEY (RuteID, TabellID),
	FOREIGN KEY (RuteID) REFERENCES Togrute(RuteID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (TabellID) REFERENCES RuteTabell(TabellID)
		ON UPDATE CASCADE
		ON UPDATE CASCADE
);

-- StopperVed
CREATE TABLE IF NOT EXISTS Vogn (
	VognID INTEGER PRIMARY KEY,
	VognNavn TEXT,
	FOREIGN KEY (VognNavn) REFERENCES VognType(VognNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

-- BruktPåRute
CREATE TABLE IF NOT EXISTS BruktPåRute (
	Kupenr INTEGER,
	VognID INTEGER,
	RuteID INTEGER,
	Ukedag TEXT,
	PRIMARY KEY (Kupenr, VognID, RuteID, Ukedag),
	FOREIGN KEY (Kupenr) REFERENCES Kupe (Kupenr)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE,
	FOREIGN KEY (VognID) REFERENCES Vogn(VognID)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE,
	FOREIGN KEY (Ukedag, RuteID) REFERENCES Ruteforekomst(Ukedag, RuteID)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Kunde (
	KundeNr INTEGER PRIMARY KEY,
	Navn TEXT,
  	Epost TEXT,
	MobilNr TEXT
);

CREATE TABLE IF NOT EXISTS KundeOrdre (
	OrdreNr INTEGER PRIMARY KEY,
	Navn TEXT,
	Epost TEXT,
	MobilNr TEXT,
	KundeNr INTEGER,
	RuteforekomstUkedag TEXT,
	TogruteID INTEGER,
	FOREIGN KEY (KundeNr) REFERENCES Kunde (KundeNr)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE,
	FOREIGN KEY (RuteforekomstUkedag, TogruteID) REFERENCES Ruteforekomst (Ukedag, RuteID)
    	ON UPDATE CASCADE
    	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Billett (
	BillettNr INTEGER PRIMARY KEY,
	SeteSengNr INTEGER,
	VognID INTEGER,
	OrdreNr INTEGER,
	FOREIGN KEY (VognID) REFERENCES Vogn(VognID)
    	ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (OrdreNr) REFERENCES KundeOrdre(OrdreNr)
    	ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Okkuperer (
	StrekningsID INTEGER,
	BillettNr INTEGER,
	PRIMARY KEY (StrekningsID, BillettNr),
	FOREIGN KEY (StrekningsID) REFERENCES Delstrekning (StrekningsID)
    	ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (BillettNr) REFERENCES Billett (BillettNr)
    	ON UPDATE CASCADE
		ON DELETE CASCADE
);